/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.battlecity;
import java.lang.String;
import java.util.Random;
import java.util.StringJoiner;
import java.util.concurrent.atomic.AtomicBoolean;


/**
 *
 * @author Miller
 */
public class window extends javax.swing.JFrame {

    String[][] mapa;
    int Column, row;
    public boolean condicionDeConexion = false;
    AtomicBoolean buttonClicked = new AtomicBoolean(false);
    TCPClient50 manejador;
    /**
     * Creates new form window
     * @param mapa
     * @param manage
     */
    public window(String[][] mapa, TCPClient50 manage) {
        this.mapa = mapa;
        this.manejador = manage;
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("value_IP"); // NOI18N

        jLabel1.setText("IP");

        jLabel2.setText("Port");

        jTextField2.setName("value_Port"); // NOI18N

        jButton1.setText("Conectar");
        jButton1.setName("botton_Conectar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("^");
        jButton2.setActionCommand("flechaArriba");
        jButton2.setName("flecha_Arriba"); // NOI18N

        jButton3.setText("<");
        jButton3.setActionCommand("flechaIzquierda");
        jButton3.setName("flecha_Izquierda"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(">");
        jButton4.setActionCommand("flechaDerecha");
        jButton4.setName("felcha_derecha"); // NOI18N

        jButton5.setText("v");
        jButton5.setActionCommand("flechaBaja");
        jButton5.setName("flecha_Baja"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(72, 72, 72)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton5))
                        .addGap(45, 45, 45)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed
*/
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        boolean search = true;
        
        

        //Generar posicion aleatoria del tanque 
        while(search){
                Random rand = new Random();
                 Column = rand.nextInt(29);
                 row = rand.nextInt(13);
                
                if(mapa[row][Column].equals(" ")){
                    mapa[row][Column] = ">";
                    condicionDeConexion =  true;
                    System.out.println(condicionDeConexion);
                    buttonClicked.set(true);
                    search = false;
                    
                    System.out.println("row y Column"+row+" "+Column);
                    
                }
                
        }
        
        //pasar la matrix al jTextArea de la GUI
        StringJoiner joiner = new StringJoiner("");
        for(int i = 0; i < 13; i++) {
            for(int j = 0; j < 29; j++) {
                //jTextArea1.setText(mapa[i][j] + " ");
                
                joiner.add(mapa[i][j]+ " ");
                //columns = jTextArea1.getColumns();
                //rows = jTextArea1.getRows();
                
                
            }
            //jTextArea1.setText("\n");
            
            joiner.add("\n");
        }
        
        //jTextArea1.setVisible(true);
        jTextArea1.setText(joiner.toString());
 
        //for (int i = 0; i < 13; i++) {
          //  for (int j = 0; j < 29; j++) {
                manejador.sendMessage(Integer.toString(row)+" "+Integer.toString(Column)+" "+mapa[row][Column]);
                
               //2 10 >
            //}
        //}
                
        System.out.println("Columnas: "+jTextArea1.getColumns()+ " Filas: "+jTextArea1.getRows());        
    }

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       int rowAntiguo, ColumnAntiguo; 
       mapa[row][Column]= " ";
       rowAntiguo = row;
       ColumnAntiguo = Column;
       Column = Column -1;
       mapa[row][Column]= "<";
       
       
       manejador.sendMessage(Integer.toString(row)+" "+Integer.toString(Column)+" "+mapa[row][Column]+ 
               " "+Integer.toString(rowAntiguo)+" "+Integer.toString(ColumnAntiguo)+" "+mapa[rowAntiguo][ColumnAntiguo]);
      // manejador.sendMessage(Integer.toString(rowAntiguo)+" "+Integer.toString(ColumnAntiguo)+" "+mapa[rowAntiguo][ColumnAntiguo]);
       
         
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextArea getJTextArea(){
        return jTextArea1;
    }

    public void setJTextArea(String letter){
        jTextArea1.append(letter);

    }

}
